version: "3"

services:

 gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - /gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=p0162978
      - OPENVPN_PASSWORD=9CxnNb8aLG
      - SERVER_REGIONS=Switzerland
      - VPN_PORT_FORWARDING=on
      - HTTP_CONTROL_SERVER_ADDRESS=:6060
      - HTTP_CONTROL_SERVER_LOG=on

    ports:
      - 9696:9696
      - 8686:8686
      - 8080:8080
      - 9090:9090
      - 6881:6881/tcp
      - 6881:6881/udp
     
 qbittorrent:
    image: emmercm/qbittorrent:latest
    container_name: qbittorent
    network_mode: service:gluetun
    restart: unless-stopped
    environment:
      - TZ=America/New_York
    volumes:
      - /home/lukas/config:/config
      - /data:/data
      - /mnt/Whole/download:/downloads
      - /mnt/Whole/download/incomplete:/incomplete
 
 sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: service:gluetun
    restart: unless-stopped
    environment:
      - PUID=0 
      - PGID=0 
      - TZ=Etc/UTC
    volumes:
      - /home/lukas/sabnzbd/config:/config
      - /mnt/Whole/download:/downloads #optional
      - /mnt/Whole/download/incomplete:/incomplete #optional    
   
